add milestone as input to tag-release

diff --git a/.github/workflows/create-release.yaml b/.github/workflows/create-release.yaml
--- a/.github/workflows/create-release.yaml
+++ b/.github/workflows/create-release.yaml
@@ -1,69 +1,72 @@
- name: "Create release"
- run-name: "Create release ${{ inputs.release_version }} with dry-run: ${{inputs.dry-run}}"
+name: "Create release"
+run-name: "Create release ${{ inputs.release_version }} with dry-run: ${{inputs.dry-run}}"
 
- permissions:
-   contents: write
+permissions:
+  contents: write
 
- on:
-   workflow_dispatch:
-     inputs:
-       release_version:
-         description: "Release version (i.e. x.y.z)"
-         default: ""
-         required: true
-       dry-run:
-         type: boolean
-         description: "Creates a dry-run branch and tag. This will not trigger the actual release process."
-         default: true
+on:
+  workflow_dispatch:
+    inputs:
+      release_version:
+        description: "Release version (i.e. x.y.z)"
+        default: ""
+        required: true
+      dry-run:
+        type: boolean
+        description: "Creates a dry-run branch and tag. This will not trigger the actual release process."
+        default: true
 
- jobs:
-   # check if tag is a valid semantic version
-   # check that no release already exists with that name
-   validate-release:
-     env:
+jobs:
+  # check if tag is a valid semantic version
+  # check that no release already exists with that name
+  validate-release:
+    env:
       GH_TOKEN: ${{ github.token }}
-     name: Validate release
-     runs-on: ubuntu-latest
-     steps:
-       # checkout code including all history
-       - name: Checkout code
-         uses: actions/checkout@v4
-         with:
-           fetch-depth: 0
-           ref: main
+    name: Validate release
+    runs-on: ubuntu-latest
+    steps:
+      # checkout code including all history
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: main
 
-       - name: Check if that release tag is correctly formatted
-         run: "./hack/scripts/check_release_tag.sh ${{ inputs.release_version }}"
+      - name: Check if that release tag is correctly formatted
+        run: "./hack/scripts/check_release_tag.sh ${{ inputs.release_version }}"
 
-       - name: Check if release tag already exists
-         run: |
-           if [ $(git tag -l ${{ inputs.release_version }}) ]; then
-             echo "::error ::Tag ${{ inputs.release_version }} already exists"
-             exit 1
-           fi
+      - name: Check if release tag already exists
+        run: |
+          if [ $(git tag -l ${{ inputs.release_version }}) ]; then
+            echo "::error ::Tag ${{ inputs.release_version }} already exists"
+            exit 1
+          fi
 
-       - name: Check for existing artifacts from previous release runs
-         run: "./hack/scripts/check_artifacts_existence.sh ${{ inputs.release_version }}"
+      - name: Check for existing artifacts from previous release runs
+        run: "./hack/scripts/check_artifacts_existence.sh ${{ inputs.release_version }}"
 
-       - name: Check if milestone exists and is closed
-         run: "./hack/scripts/check_milestone.sh ${{ github.repository }} ${{ inputs.release_version }}"
+      - name: Check if milestone exists and is closed
+        run: "./hack/scripts/check_milestone.sh ${{ github.repository }} ${{ inputs.release_version }}"
 
-       # create a branch for the release and push it to the repository
-       - name: Create release branch (dry-run)
-         if: ${{ inputs.dry-run == true }}
-         run: "./hack/scripts/create_branch_and_tag.sh -v ${{ inputs.release_version }} -r origin -d"
+      # create a branch for the release and push it to the repository
+      - name: Create release branch (dry-run)
+        if: ${{ inputs.dry-run == true }}
+        run: "./hack/scripts/create_branch_and_tag.sh -v ${{ inputs.release_version }} -r origin -d"
 
-       - name: Create release branch
-         if: ${{ inputs.dry-run == false }}
-         run: "./hack/scripts/create_branch_and_tag.sh -v ${{ inputs.release_version }} -r origin"
+      - name: Create release branch
+        if: ${{ inputs.dry-run == false }}
+        run: "./hack/scripts/create_branch_and_tag.sh -v ${{ inputs.release_version }} -r origin"
 
-       # run tag-release workflow
+      # run tag-release workflow
 
-   publish-release:
-       needs:
-         - validate-release
-       uses: ./.github/workflows/tag-release.yml
-       permissions:
-         id-token: write
-         contents: write
-       if: inputs.dry-run == false
+  publish-release:
+    needs:
+      - validate-release
+    uses: ./.github/workflows/tag-release.yml
+    with:
+      milestone: ${{ inputs.release_version }}
+
+    permissions:
+      id-token: write
+      contents: write
+    if: inputs.dry-run == false
